[package]
name = "deno-limits"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
deno_console = "0.98"
deno_core = "0.180"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1", features = ["full"] }
